#include "Arduino.h"
// WHEN IN POSITION
// SCAN CROPS
// MODEL WHICH IS NOT A CROP
// FLAG IT AS A WEED
// DIRECT THE DIODE GANTRY
// TOGGLE THE 20W LASER DIODE BY 5KHZ PWM
// LOG REPORT
// CONTINUE MOTION
